config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  # resources :library_229s
  # resources :students_books
  # resources :students
  # devise_for :users
  resources :friends
  # resources :names
  get 'pages/home'
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :phone, :email)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <%# <th scope="row">friend.id</th> %>
  <td><%= friend.name %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.email %></td>
  <td>
    <%= link_to "Show", friend, class: 'btn btn-info' %>
    <%= link_to "New", new_friend_path, class: 'btn btn-primary' %>
    <%= button_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
  </>
</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Friends</h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <%# <th scope="col">#</th> %>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Phone</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <%# <--<%= render friend %>
      <tr id="<%= dom_id friend %>">
        <td><%= friend.name %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.email %></td>
        <td>
          <%= link_to "Show", friend, class: 'btn btn-outline-info' %>
        </td>
        <td>
          <%= link_to "New", new_friend_path, class: 'btn btn-outline-primary' %>
        </td>
        <td>
          <%= button_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</tbody>
<%= link_to "New friend", new_friend_path, class: 'btn btn-success'%>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @friend %>
<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %>
  <%= link_to "Back to friends", friends_path %>
  <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-outline-danger btn-sm"  %>
</div>