config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  # resources :library_229s
  # resources :students_books
  # resources :students
  # devise_for :users
  resources :friends
  # resources :names
  get 'pages/home'
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/library.rb
class Library < ApplicationRecord
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]

  # GET /libraries or /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to library_url(@library), notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to library_url(@library), notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.require(:library).permit(:IdStudent_229, :NameStudent_229, :RoomStudent_229, :IdBook_229, :NameBook_229, :Author_229, :CategoryBook_229, :IdBM_229, :DateBorrow_229, :DateBack_229, :numberDate_229)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>
      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.text_field :IdStudent_229 %>
  </div>
  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :NameStudent_229 %>
  </div>
  <div>
    <%= form.label :Class, style: "display: block" %>
    <%= form.text_field :RoomStudent_229 %>
  </div>
  <div>
    <%= form.label :IdBook, style: "display: block" %>
    <%= form.text_field :IdBook_229 %>
  </div>
  <div>
    <%= form.label :TitleBook, style: "display: block" %>
    <%= form.text_field :NameBook_229 %>
  </div>
  <div>
    <%= form.label :Author, style: "display: block" %>
    <%= form.text_field :Author_229 %>
  </div>
  <div>
    <%= form.label :CategoryBook, style: "display: block" %>
    <%= form.text_field :CategoryBook_229 %>
  </div>
  <div>
    <%= form.label :IdBM, style: "display: block" %>
    <%= form.text_field :IdBM_229 %>
  </div>
  <div>
    <%= form.label :DateBorrow, style: "display: block" %>
    <%= form.text_field :DateBorrow_229 %>
  </div>
  <div>
    <%= form.label :DateBack, style: "display: block" %>
    <%= form.text_field :DateBack_229 %>
  </div>
  <div>
    <%= form.label :numberDay, style: "display: block" %>
    <%= form.text_field :numberDate_229 %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_library.html.erb
<h1>Information Borrow</h1>
<div id="<%= dom_id library %>">
  <p>
    <strong>Idstudent 229:</strong>
    <%= library.IdStudent_229 %>
  </p>
  <p>
    <strong>Namestudent 229:</strong>
    <%= library.NameStudent_229 %>
  </p>
  <p>
    <strong>Roomstudent 229:</strong>
    <%= library.RoomStudent_229 %>
  </p>
  <p>
    <strong>Idbook 229:</strong>
    <%= library.IdBook_229 %>
  </p>
  <p>
    <strong>Namebook 229:</strong>
    <%= library.NameBook_229 %>
  </p>
  <p>
    <strong>Author 229:</strong>
    <%= library.Author_229 %>
  </p>
  <p>
    <strong>Categorybook 229:</strong>
    <%= library.CategoryBook_229 %>
  </p>
  <p>
    <strong>Idbm 229:</strong>
    <%= library.IdBM_229 %>
  </p>
  <p>
    <strong>Dateborrow 229:</strong>
    <%= library.IdBM_229 %>
  </p>
  <p>
    <strong>Dateback 229:</strong>
    <%= library.DateBorrow_229 %>
  </p>
  <p>
    <strong>Dateback 229:</strong>
    <%= library.DateBack_229 %>
  </p>
  <p>
    <strong>Numberdate 229:</strong>
    <%= library.numberDate_229 %>
  </p>
</div>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Libraries</h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Mã HS</th>
      <th scope="col">Họ và Tên</th>
      <th scope="col">Lớp</th>
      <th scope="col">Mã Sách</th>
      <th scope="col">Tên Sách</th>
      <th scope="col">Tên Tác Giả</th>
      <th scope="col">Tủ Sách</th>
      <th scope="col">Số BM </th>
      <th scope="col">Ngày Mượn</th>
      <th scope="col">Ngày Trả</th>
      <th scope="col">Số Ngày</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @libraries.each do |library| %>
      <%# <%= render library %>
      <tr id="<%= dom_id library %>">
        <td><%= library.IdStudent_229 %></td>
        <td><%= library.NameStudent_229 %></td>
        <td><%= library.RoomStudent_229 %></td>
        <td><%= library.IdBook_229 %></td>
        <td><%= library.NameBook_229 %></td>
        <td><%= library.Author_229 %></td>
        <td><%= library.CategoryBook_229 %></td>
        <td><%= library.IdBM_229 %></td>
        <td><%= library.DateBorrow_229 %></td>
        <td><%= library.DateBack_229 %></td>
        <td><%= library.numberDate_229 %></td>
        <td>
          <%= link_to "Show", library, class: 'btn btn-outline-info' %>
        </td>
        <td>
          <%= button_to 'Delete', library, method: :delete, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%# <div id="libraries"> %>
<%# </div> %>
<%= link_to "New library", new_library_path, class: 'btn btn-outline-primary' %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @library %>

<div>
  <%= link_to "Edit this library", edit_library_path(@library) %> |
  <%= link_to "Back to libraries", libraries_path %>

  <%= button_to "Destroy this library", @library, method: :delete %>
</div>